const users = [
    {
        name: {
            first: "Admin - Eliyahu",
            middle: "",
            last: "Levi",
        },
        phone: "0507123012",
        email: "adminE@gmail.com",
        password: "Abc!123Abc",
        address: {
            state: "IL",
            country: "Israel",
            city: "Tel aviv",
            street: "Herzel",
            houseNumber: 5,
            zip: "8920435",
        },

        isBusiness: true,
        isAdmin: true,

    },
    {
        "name": {
            "first": "Admin - Idan",
            "middle": "",
            "last": "Ofek"
        },
        "phone": "0507123011",
        "email": "adminI@gmail.com",
        "password": "Abc!123Abc",
        "address": {
            "state": "NY",
            "country": "USA",
            "city": "New York",
            "street": "5th Avenue",
            "houseNumber": 3,
            "zip": "10001"
        },

        "isBusiness": true,
        "isAdmin": true
    },
    {
        "name": {
            "first": "Admin - Uriel",
            "middle": "",
            "last": "Neuberger"
        },
        "phone": "0507123022",
        "email": "adminU@gmail.com",
        "password": "Abc!123Abc",
        "address": {
            "state": "CA",
            "country": "USA",
            "city": "Los Angeles",
            "street": "Sunset Blvd",
            "houseNumber": 2,
            "zip": "90001"
        },

        "isBusiness": true,
        "isAdmin": false
    }

];


const patients = [
    {
        "firstName": "David",
        "lastName": "Lee",
        "patientDOB": "2014-05-10",
        "patientGender": "Male",
        "patientZipCode": "60280",
        "providers": "AMD",
        "providerURL": "http://provider-url12.com",
        "treatmentDate": "2024-05-19",
        "startTime": "13:30:00",
        "endTime": "13:35:00",
        "features": "Additional features",
        "meetingType": "Follow-up",
        "dayStart": "23/07/2024",
        "dayEnd": "23/07/2024",
        "url": "http://another-url12.com",
        "userActivity": "Another activity log",
        "comments": "Patient needs more follow-up."
    },
    {
        "firstName": "David",
        "lastName": "Le",
        "patientDOB": "2014-05-10",
        "patientGender": "Male",
        "patientZipCode": "67280",
        "providers": "Quest",
        "providerURL": "http://provider-url22.com",
        "treatmentDate": "2024-05-19",
        "startTime": "13:30:00",
        "endTime": "13:45:00",
        "features": "Additional features",
        "meetingType": "Follow-up",
        "dayStart": "23/07/2024",
        "dayEnd": "23/07/2024",
        "url": "http://another-url22.com",
        "userActivity": "Another activity log",
        "comments": "Patient needs more follow-up."
    },
    {
        "firstName": "Emily",
        "lastName": "Clark",
        "patientDOB": "2013-08-21",
        "patientGender": "Female",
        "patientZipCode": "67340",
        "providers": "AMD",
        "providerURL": "http://provider-url11.com",
        "treatmentDate": "2024-06-05",
        "startTime": "09:00:00",
        "endTime": "09:07:00",
        "features": "Routine check-up",
        "meetingType": "Initial consultation",
        "dayStart": "24/07/2024",
        "dayEnd": "24/07/2024",
        "url": "http://another-url11.com",
        "userActivity": "Patient checked-in",
        "comments": "No immediate concerns."
    },
    {
        "firstName": "Emly",
        "lastName": "Clak",
        "patientDOB": "2013-08-21",
        "patientGender": "Female",
        "patientZipCode": "69340",
        "providers": "Behavidance",
        "providerURL": "http://provider-url31.com",
        "treatmentDate": "2024-06-05",
        "startTime": "09:00:00",
        "endTime": "09:15:00",
        "features": "Routine check-up",
        "meetingType": "Initial consultation",
        "dayStart": "25/07/2024",
        "dayEnd": "25/07/2024",
        "url": "http://another-url31.com",
        "userActivity": "Patient checked-in",
        "comments": "No immediate concerns."
    },
    {
        "firstName": "Michael",
        "lastName": "Johnson",
        "patientDOB": "2015-12-15",
        "patientGender": "Male",
        "patientZipCode": "67500",
        "providers": "AMD",
        "providerURL": "http://provider-url.com",
        "treatmentDate": "2024-07-10",
        "startTime": "14:00:00",
        "endTime": "14:30:00",
        "features": "Dental cleaning",
        "meetingType": "Routine appointment",
        "dayStart": "25/07/2024",
        "dayEnd": "25/07/2024",
        "url": "http://another-url.com",
        "userActivity": "Patient received treatment",
        "comments": "Schedule next cleaning in six months."
    },
    {
        "firstName": "Michal",
        "lastName": "Johson",
        "patientDOB": "2015-12-15",
        "patientGender": "Male",
        "patientZipCode": "67760",
        "providers": "eCW",
        "providerURL": "http://provider-url.55com",
        "treatmentDate": "2024-07-10",
        "startTime": "13:00:00",
        "endTime": "13:15:00",
        "features": "Dental cleaning",
        "meetingType": "Routine appointment",
        "dayStart": "27/07/2024",
        "dayEnd": "27/07/2024",
        "url": "http://another-url55.com",
        "userActivity": "Patient received treatment",
        "comments": "Schedule next cleaning in six months."
    },
    {
        "firstName": "Sarah",
        "lastName": "Williams",
        "patientDOB": "2016-01-25",
        "patientGender": "Female",
        "patientZipCode": "67650",
        "providers": "AMD",
        "providerURL": "http://provider-url19.com",
        "treatmentDate": "2024-07-02",
        "startTime": "11:30:00",
        "endTime": "11:47:00",
        "features": "Eye exam",
        "meetingType": "Routine appointment",
        "dayStart": "29/07/2024",
        "dayEnd": "29/07/2024",
        "url": "http://another-url19.com",
        "userActivity": "Patient checked-in",
        "comments": "Prescription updated."
    },
    {
        "firstName": "Sara",
        "lastName": "William",
        "patientDOB": "2016-01-25",
        "patientGender": "Female",
        "patientZipCode": "67654",
        "providers": "eCW",
        "providerURL": "http://provider-url1.com",
        "treatmentDate": "2024-07-02",
        "startTime": "10:30:00",
        "endTime": "10:40:00",
        "features": "Eye exam",
        "meetingType": "Routine appointment",
        "dayStart": "26/07/2024",
        "dayEnd": "26/07/2024",
        "url": "http://another-url1.com",
        "userActivity": "Patient checked-in",
        "comments": "Prescription updated."
    },
    {
        "firstName": "John",
        "lastName": "Davis",
        "patientDOB": "2012-03-05",
        "patientGender": "Male",
        "patientZipCode": "67700",
        "providers": "eCW",
        "providerURL": "http://provider-url2.com",
        "treatmentDate": "2024-07-18",
        "startTime": "15:00:00",
        "endTime": "15:10:00",
        "features": "Physical therapy",
        "meetingType": "Follow-up",
        "dayStart": "27/07/2024",
        "dayEnd": "27/07/2024",
        "url": "http://another-url2.com",
        "userActivity": "Patient attended session",
        "comments": "Improvement noted, continue exercises."
    },
    {
        "firstName": "Anna",
        "lastName": "Martinez",
        "patientDOB": "2011-11-20",
        "patientGender": "Female",
        "patientZipCode": "67810",
        "providers": "eCW",
        "providerURL": "http://provider-url3.com",
        "treatmentDate": "2024-08-01",
        "startTime": "11:00:00",
        "endTime": "12:00:00",
        "features": "Orthopedic consultation",
        "meetingType": "Initial consultation",
        "dayStart": "28/07/2024",
        "dayEnd": "28/07/2024",
        "url": "http://another-url3.com",
        "userActivity": "Patient checked-in",
        "comments": "Discussed treatment options."
    },
    {
        "firstName": "James",
        "lastName": "Garcia",
        "patientDOB": "2013-06-30",
        "patientGender": "Male",
        "patientZipCode": "67920",
        "providers": "Quest",
        "providerURL": "http://provider-url4.com",
        "treatmentDate": "2024-08-10",
        "startTime": "12:30:00",
        "endTime": "12:40:00",
        "features": "Lab tests",
        "meetingType": "Routine appointment",
        "dayStart": "29/07/2024",
        "dayEnd": "29/07/2024",
        "url": "http://another-url4.com",
        "userActivity": "Patient provided samples",
        "comments": "Results expected in 2 days."
    },
    {
        "firstName": "Sophia",
        "lastName": "Hernandez",
        "patientDOB": "2014-02-15",
        "patientGender": "Female",
        "patientZipCode": "68030",
        "providers": "Quest",
        "providerURL": "http://provider-url5.com",
        "treatmentDate": "2024-08-20",
        "startTime": "09:30:00",
        "endTime": "09:45:00",
        "features": "Blood test",
        "meetingType": "Routine appointment",
        "dayStart": "30/07/2024",
        "dayEnd": "30/07/2024",
        "url": "http://another-url5.com",
        "userActivity": "Patient provided samples",
        "comments": "Follow-up for results."
    },
    {
        "firstName": "Matthew",
        "lastName": "Rodriguez",
        "patientDOB": "2012-07-25",
        "patientGender": "Male",
        "patientZipCode": "68140",
        "providers": "Quest",
        "providerURL": "http://provider-url6.com",
        "treatmentDate": "2024-09-01",
        "startTime": "08:00:00",
        "endTime": "08:05:00",
        "features": "Diagnostic imaging",
        "meetingType": "Initial consultation",
        "dayStart": "31/07/2024",
        "dayEnd": "31/07/2024",
        "url": "http://another-url6.com",
        "userActivity": "Patient received imaging",
        "comments": "Awaiting results."
    },
    {
        "firstName": "Isabella",
        "lastName": "Lopez",
        "patientDOB": "2015-09-10",
        "patientGender": "Female",
        "patientZipCode": "68250",
        "providers": "Behavidance",
        "providerURL": "http://provider-url7.com",
        "treatmentDate": "2024-09-10",
        "startTime": "13:00:00",
        "endTime": "14:00:00",
        "features": "Behavioral assessment",
        "meetingType": "Initial consultation",
        "dayStart": "01/08/2024",
        "dayEnd": "01/08/2024",
        "url": "http://another-url7.com",
        "userActivity": "Patient attended assessment",
        "comments": "Plan for follow-up sessions."
    },
    {
        "firstName": "Mia",
        "lastName": "Wilson",
        "patientDOB": "2013-04-05",
        "patientGender": "Female",
        "patientZipCode": "68360",
        "providers": "Behavidance",
        "providerURL": "http://provider-url8.com",
        "treatmentDate": "2024-09-20",
        "startTime": "15:30:00",
        "endTime": "15:45:00",
        "features": "Therapy session",
        "meetingType": "Follow-up",
        "dayStart": "02/08/2024",
        "dayEnd": "02/08/2024",
        "url": "http://another-url8.com",
        "userActivity": "Patient attended session",
        "comments": "Positive progress observed."
    },
    {
        "firstName": "Ethan",
        "lastName": "Anderson",
        "patientDOB": "2011-10-25",
        "patientGender": "Male",
        "patientZipCode": "68470",
        "providers": "Behavidance",
        "providerURL": "http://provider-url9.com",
        "treatmentDate": "2024-10-01",
        "startTime": "14:30:00",
        "endTime": "15:30:00",
        "features": "Counseling",
        "meetingType": "Routine appointment",
        "dayStart": "03/08/2024",
        "dayEnd": "03/08/2024",
        "url": "http://another-url9.com",
        "userActivity": "Patient attended session",
        "comments": "Scheduled next session."
    }
];


export { users, patients };